variables:
  FF_USE_FASTZIP: 1

image: lnl7/nix

# Override git urls to use ci-job-token
before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf git://gitlab.com
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf ssh://git@gitlab.com
  - git config --global url."https://ancient123:${GITHUB_ACCESS_TOKEN}@github.com/".insteadOf git://github.com
  - git config --global url."https://ancient123:${GITHUB_ACCESS_TOKEN}@github.com/".insteadOf ssh://git@github.com
  - git config --global url."https://dl.cloudsmith.io/${CLOUDSMITH_ENTITLEMENT}/".insteadOf https://dl.cloudsmith.io/basic/
  - echo ""

lint:
  tags:
    - docker
  script:
    - nix-shell --run "prepend-timestamps lint-ci"

test:
  tags:
    - docker
  script:
    - nix-shell --run "prepend-timestamps cape-test-geth"
    # - nix-shell --run cape-test-brownie # TODO not working at the moment
  cache:
    key: cape-test
    paths:
      - .cargo/
      - target/

doc:
  tags:
    - docker
  script:
    - nix-shell --run "prepend-timestamps make-doc"
  artifacts:
    paths:
      - doc
