[package]
name = "cape-workflow"
version = "0.1.0"
authors = ["Espresso Systems <hello@espressosys.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
cap-rust-sandbox = { path = "../../contracts/rust" }
jf-utils = { features=["std"], git = "ssh://git@github.com/EspressoSystems/jellyfish.git" }
jf-rescue = { features=["std"], git = "ssh://git@github.com/EspressoSystems/jellyfish.git" }
jf-cap = { features = ["test_apis"], git = "ssh://git@github.com/EspressoSystems/cap.git", rev = "16ad157f96d2102d59206df0106fb341302180d3" }

ethers = { git = "https://github.com/gakonst/ethers-rs", features = ["abigen"] }

serde_json = "1.0.67"
serde = { version = "1.0.124", features = ["derive"] }
rand = "0.8.4"
itertools = "0.10.1"
